/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Class.Navegador;
import javax.swing.JOptionPane;

/**
 *
 * @author sebas
 */
public class Gamen5x5 extends javax.swing.JFrame {
    Navegador Nav;
    public int tab5x5[][];
    int ganador;
    int movimientos = 0;
    boolean turnoP1 = true;
    boolean turnoP2 = false;
    public Gamen5x5(Navegador n) {
        initComponents();
        Nav = n;
        tab5x5 = new int[5][5];
        txtMov.setText(String.valueOf(movimientos));
        if(Nav.gui.chkCircle1.isSelected()){
            txtTurno.setText("X");
        } else {
            txtTurno.setText("O");
        }
    }

    public int getMovimientos() {
        return movimientos;
    }

    public void setMovimientos(int movimientos) {
        this.movimientos = movimientos;
    }

    public boolean isTurnoP1() {
        return turnoP1;
    }

    public void setTurnoP1(boolean turnoP1) {
        this.turnoP1 = turnoP1;
    }

    public boolean isTurnoP2() {
        return turnoP2;
    }

    public void setTurnoP2(boolean turnoP2) {
        this.turnoP2 = turnoP2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn01 = new javax.swing.JToggleButton();
        btn19 = new javax.swing.JToggleButton();
        btn18 = new javax.swing.JToggleButton();
        btn17 = new javax.swing.JToggleButton();
        btn16 = new javax.swing.JToggleButton();
        btn11 = new javax.swing.JToggleButton();
        btn12 = new javax.swing.JToggleButton();
        btn13 = new javax.swing.JToggleButton();
        btn14 = new javax.swing.JToggleButton();
        btn09 = new javax.swing.JToggleButton();
        btn08 = new javax.swing.JToggleButton();
        btn07 = new javax.swing.JToggleButton();
        btn06 = new javax.swing.JToggleButton();
        btn02 = new javax.swing.JToggleButton();
        btn03 = new javax.swing.JToggleButton();
        btn04 = new javax.swing.JToggleButton();
        txtTamaño = new javax.swing.JLabel();
        txtTurno = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMov = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btn21 = new javax.swing.JToggleButton();
        btn05 = new javax.swing.JToggleButton();
        btn10 = new javax.swing.JToggleButton();
        btn15 = new javax.swing.JToggleButton();
        btn20 = new javax.swing.JToggleButton();
        btn25 = new javax.swing.JToggleButton();
        btn24 = new javax.swing.JToggleButton();
        btn23 = new javax.swing.JToggleButton();
        btn22 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn01.setBackground(new java.awt.Color(204, 204, 204));
        btn01.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        btn01.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn01ActionPerformed(evt);
            }
        });
        getContentPane().add(btn01, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 70, 70));

        btn19.setBackground(new java.awt.Color(204, 204, 204));
        btn19.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        btn19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn19ActionPerformed(evt);
            }
        });
        getContentPane().add(btn19, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 70, 70));

        btn18.setBackground(new java.awt.Color(204, 204, 204));
        btn18.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        btn18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn18ActionPerformed(evt);
            }
        });
        getContentPane().add(btn18, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 70, 70));

        btn17.setBackground(new java.awt.Color(204, 204, 204));
        btn17.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        btn17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn17ActionPerformed(evt);
            }
        });
        getContentPane().add(btn17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 70, 70));

        btn16.setBackground(new java.awt.Color(204, 204, 204));
        btn16.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        btn16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn16ActionPerformed(evt);
            }
        });
        getContentPane().add(btn16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 70, 70));

        btn11.setBackground(new java.awt.Color(204, 204, 204));
        btn11.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        btn11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });
        getContentPane().add(btn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 70, 70));

        btn12.setBackground(new java.awt.Color(204, 204, 204));
        btn12.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        btn12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });
        getContentPane().add(btn12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 70, 70));

        btn13.setBackground(new java.awt.Color(204, 204, 204));
        btn13.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        btn13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn13ActionPerformed(evt);
            }
        });
        getContentPane().add(btn13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 70, 70));

        btn14.setBackground(new java.awt.Color(204, 204, 204));
        btn14.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        btn14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn14ActionPerformed(evt);
            }
        });
        getContentPane().add(btn14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 70, 70));

        btn09.setBackground(new java.awt.Color(204, 204, 204));
        btn09.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        btn09.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn09ActionPerformed(evt);
            }
        });
        getContentPane().add(btn09, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 70, 70));

        btn08.setBackground(new java.awt.Color(204, 204, 204));
        btn08.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        btn08.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn08ActionPerformed(evt);
            }
        });
        getContentPane().add(btn08, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 70, 70));

        btn07.setBackground(new java.awt.Color(204, 204, 204));
        btn07.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        btn07.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn07ActionPerformed(evt);
            }
        });
        getContentPane().add(btn07, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 70, 70));

        btn06.setBackground(new java.awt.Color(204, 204, 204));
        btn06.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        btn06.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn06ActionPerformed(evt);
            }
        });
        getContentPane().add(btn06, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 70, 70));

        btn02.setBackground(new java.awt.Color(204, 204, 204));
        btn02.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        btn02.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn02ActionPerformed(evt);
            }
        });
        getContentPane().add(btn02, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 70, 70));

        btn03.setBackground(new java.awt.Color(204, 204, 204));
        btn03.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        btn03.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn03ActionPerformed(evt);
            }
        });
        getContentPane().add(btn03, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 70, 70));

        btn04.setBackground(new java.awt.Color(204, 204, 204));
        btn04.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        btn04.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn04ActionPerformed(evt);
            }
        });
        getContentPane().add(btn04, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 70, 70));

        txtTamaño.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        txtTamaño.setForeground(new java.awt.Color(255, 0, 0));
        txtTamaño.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTamaño.setText("5x5");
        txtTamaño.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(txtTamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 70, -1));

        txtTurno.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTurno.setForeground(new java.awt.Color(255, 0, 0));
        txtTurno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTurno.setText("00");
        txtTurno.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(txtTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 60, 30));

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("TURNO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, -1, 10));

        txtMov.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtMov.setForeground(new java.awt.Color(255, 0, 0));
        txtMov.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMov.setText("00");
        getContentPane().add(txtMov, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 40, 50));

        btnBack.setBackground(new java.awt.Color(204, 204, 204));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 0, 0));
        btnBack.setText("Menú principal");
        btnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 180, 40));

        btn21.setBackground(new java.awt.Color(204, 204, 204));
        btn21.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        btn21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn21ActionPerformed(evt);
            }
        });
        getContentPane().add(btn21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 70, 70));

        btn05.setBackground(new java.awt.Color(204, 204, 204));
        btn05.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        btn05.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn05ActionPerformed(evt);
            }
        });
        getContentPane().add(btn05, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 70, 70));

        btn10.setBackground(new java.awt.Color(204, 204, 204));
        btn10.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        btn10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });
        getContentPane().add(btn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 70, 70));

        btn15.setBackground(new java.awt.Color(204, 204, 204));
        btn15.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        btn15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn15ActionPerformed(evt);
            }
        });
        getContentPane().add(btn15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 70, 70));

        btn20.setBackground(new java.awt.Color(204, 204, 204));
        btn20.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        btn20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn20ActionPerformed(evt);
            }
        });
        getContentPane().add(btn20, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 70, 70));

        btn25.setBackground(new java.awt.Color(204, 204, 204));
        btn25.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        btn25.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn25ActionPerformed(evt);
            }
        });
        getContentPane().add(btn25, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 70, 70));

        btn24.setBackground(new java.awt.Color(204, 204, 204));
        btn24.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        btn24.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn24ActionPerformed(evt);
            }
        });
        getContentPane().add(btn24, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 70, 70));

        btn23.setBackground(new java.awt.Color(204, 204, 204));
        btn23.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        btn23.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn23ActionPerformed(evt);
            }
        });
        getContentPane().add(btn23, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 70, 70));

        btn22.setBackground(new java.awt.Color(204, 204, 204));
        btn22.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        btn22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn22ActionPerformed(evt);
            }
        });
        getContentPane().add(btn22, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 70, 70));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 50, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn01ActionPerformed
        if(turnoP1){
            txtTurno.setForeground(Nav.game.player2.getColor());
            turnoP1 = false;
        } else {
            txtTurno.setForeground(Nav.game.player1.getColor());
            turnoP1 = true;
        }
        movimientos++;
        txtMov.setText(String.valueOf(movimientos));
        btn01.setText(txtTurno.getText());
        btn01.setEnabled(false);
        Nav.board.colocarFicha();
        if("X".equals(txtTurno.getText())){
            tab5x5[0][0] = 1;
        } else {
            tab5x5[0][0] = 2;
        }
        ganador = Nav.game.hayGanador5x5(tab5x5);
        Nav.game.elegirGanador(ganador, movimientos);
    }//GEN-LAST:event_btn01ActionPerformed

    private void btn19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn19ActionPerformed
        if(turnoP1){
            txtTurno.setForeground(Nav.game.player2.getColor());
            turnoP1 = false;
        } else {
            txtTurno.setForeground(Nav.game.player1.getColor());
            turnoP1 = true;
        }
        movimientos++;
        txtMov.setText(String.valueOf(movimientos));
        btn19.setText(txtTurno.getText());
        btn19.setEnabled(false);
        Nav.board.colocarFicha();
        if("X".equals(txtTurno.getText())){
            tab5x5[3][3] = 1;
        } else {
            tab5x5[3][3] = 2;
        }
        ganador = Nav.game.hayGanador5x5(tab5x5);
        Nav.game.elegirGanador(ganador, movimientos);
    }//GEN-LAST:event_btn19ActionPerformed

    private void btn18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn18ActionPerformed
        if(turnoP1){
            txtTurno.setForeground(Nav.game.player2.getColor());
            turnoP1 = false;
        } else {
            txtTurno.setForeground(Nav.game.player1.getColor());
            turnoP1 = true;
        }
        movimientos++;
        txtMov.setText(String.valueOf(movimientos));
        btn18.setText(txtTurno.getText());
        btn18.setEnabled(false);
        Nav.board.colocarFicha();
        if("X".equals(txtTurno.getText())){
            tab5x5[3][2] = 1;
        } else {
            tab5x5[3][2] = 2;
        }
        ganador = Nav.game.hayGanador5x5(tab5x5);
        Nav.game.elegirGanador(ganador, movimientos);
    }//GEN-LAST:event_btn18ActionPerformed

    private void btn17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn17ActionPerformed
        if(turnoP1){
            txtTurno.setForeground(Nav.game.player2.getColor());
            turnoP1 = false;
        } else {
            txtTurno.setForeground(Nav.game.player1.getColor());
            turnoP1 = true;
        }
        movimientos++;
        txtMov.setText(String.valueOf(movimientos));
        btn17.setText(txtTurno.getText());
        btn17.setEnabled(false);
        Nav.board.colocarFicha();
        if("X".equals(txtTurno.getText())){
            tab5x5[3][1] = 1;
        } else {
            tab5x5[3][1] = 2;
        }
        ganador = Nav.game.hayGanador5x5(tab5x5);
        Nav.game.elegirGanador(ganador, movimientos);
    }//GEN-LAST:event_btn17ActionPerformed

    private void btn16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn16ActionPerformed
        if(turnoP1){
            txtTurno.setForeground(Nav.game.player2.getColor());
            turnoP1 = false;
        } else {
            txtTurno.setForeground(Nav.game.player1.getColor());
            turnoP1 = true;
        }
        movimientos++;
        txtMov.setText(String.valueOf(movimientos));
        btn16.setText(txtTurno.getText());
        btn16.setEnabled(false);
        Nav.board.colocarFicha();
        if("X".equals(txtTurno.getText())){
            tab5x5[3][0] = 1;
        } else {
            tab5x5[3][0] = 2;
        }
        ganador = Nav.game.hayGanador5x5(tab5x5);
        Nav.game.elegirGanador(ganador, movimientos);
    }//GEN-LAST:event_btn16ActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        if(turnoP1){
            txtTurno.setForeground(Nav.game.player2.getColor());
            turnoP1 = false;
        } else {
            txtTurno.setForeground(Nav.game.player1.getColor());
            turnoP1 = true;
        }
        movimientos++;
        txtMov.setText(String.valueOf(movimientos));
        btn11.setText(txtTurno.getText());
        btn11.setEnabled(false);
        Nav.board.colocarFicha();
        if("X".equals(txtTurno.getText())){
            tab5x5[2][0] = 1;
        } else {
            tab5x5[2][0] = 2;
        }
        ganador = Nav.game.hayGanador5x5(tab5x5);
        Nav.game.elegirGanador(ganador, movimientos);
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        if(turnoP1){
            txtTurno.setForeground(Nav.game.player2.getColor());
            turnoP1 = false;
        } else {
            txtTurno.setForeground(Nav.game.player1.getColor());
            turnoP1 = true;
        }
        movimientos++;
        txtMov.setText(String.valueOf(movimientos));
        btn12.setText(txtTurno.getText());
        btn12.setEnabled(false);
        Nav.board.colocarFicha();
        if("X".equals(txtTurno.getText())){
            tab5x5[2][1] = 1;
        } else {
            tab5x5[2][1] = 2;
        }
        ganador = Nav.game.hayGanador5x5(tab5x5);
        Nav.game.elegirGanador(ganador, movimientos);
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn13ActionPerformed
        if(turnoP1){
            txtTurno.setForeground(Nav.game.player2.getColor());
            turnoP1 = false;
        } else {
            txtTurno.setForeground(Nav.game.player1.getColor());
            turnoP1 = true;
        }
        movimientos++;
        txtMov.setText(String.valueOf(movimientos));
        btn13.setText(txtTurno.getText());
        btn13.setEnabled(false);
        Nav.board.colocarFicha();
        if("X".equals(txtTurno.getText())){
            tab5x5[2][2] = 1;
        } else {
            tab5x5[2][2] = 2;
        }
        ganador = Nav.game.hayGanador5x5(tab5x5);
        Nav.game.elegirGanador(ganador, movimientos);
    }//GEN-LAST:event_btn13ActionPerformed

    private void btn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn14ActionPerformed
        if(turnoP1){
            txtTurno.setForeground(Nav.game.player2.getColor());
            turnoP1 = false;
        } else {
            txtTurno.setForeground(Nav.game.player1.getColor());
            turnoP1 = true;
        }
        movimientos++;
        txtMov.setText(String.valueOf(movimientos));
        btn14.setText(txtTurno.getText());
        btn14.setEnabled(false);
        Nav.board.colocarFicha();
        if("X".equals(txtTurno.getText())){
            tab5x5[2][3] = 1;
        } else {
            tab5x5[2][3] = 2;
        }
        ganador = Nav.game.hayGanador5x5(tab5x5);
        Nav.game.elegirGanador(ganador, movimientos);
    }//GEN-LAST:event_btn14ActionPerformed

    private void btn09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn09ActionPerformed
        if(turnoP1){
            txtTurno.setForeground(Nav.game.player2.getColor());
            turnoP1 = false;
        } else {
            txtTurno.setForeground(Nav.game.player1.getColor());
            turnoP1 = true;
        }
        movimientos++;
        txtMov.setText(String.valueOf(movimientos));
        btn09.setText(txtTurno.getText());
        btn09.setEnabled(false);
        Nav.board.colocarFicha();
        if("X".equals(txtTurno.getText())){
            tab5x5[1][3] = 1;
        } else {
            tab5x5[1][3] = 2;
        }
        ganador = Nav.game.hayGanador5x5(tab5x5);
        Nav.game.elegirGanador(ganador, movimientos);
    }//GEN-LAST:event_btn09ActionPerformed

    private void btn08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn08ActionPerformed
        if(turnoP1){
            txtTurno.setForeground(Nav.game.player2.getColor());
            turnoP1 = false;
        } else {
            txtTurno.setForeground(Nav.game.player1.getColor());
            turnoP1 = true;
        }
        movimientos++;
        txtMov.setText(String.valueOf(movimientos));
        btn08.setText(txtTurno.getText());
        btn08.setEnabled(false);
        Nav.board.colocarFicha();
        if("X".equals(txtTurno.getText())){
            tab5x5[1][2] = 1;
        } else {
            tab5x5[1][2] = 2;
        }
        ganador = Nav.game.hayGanador5x5(tab5x5);
        Nav.game.elegirGanador(ganador, movimientos);
    }//GEN-LAST:event_btn08ActionPerformed

    private void btn07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn07ActionPerformed
        if(turnoP1){
            txtTurno.setForeground(Nav.game.player2.getColor());
            turnoP1 = false;
        } else {
            txtTurno.setForeground(Nav.game.player1.getColor());
            turnoP1 = true;
        }
        movimientos++;
        txtMov.setText(String.valueOf(movimientos));
        btn07.setText(txtTurno.getText());
        btn07.setEnabled(false);
        Nav.board.colocarFicha();
        if("X".equals(txtTurno.getText())){
            tab5x5[1][1] = 1;
        } else {
            tab5x5[1][1] = 2;
        }
        ganador = Nav.game.hayGanador5x5(tab5x5);
        Nav.game.elegirGanador(ganador, movimientos);
    }//GEN-LAST:event_btn07ActionPerformed

    private void btn06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn06ActionPerformed
        if(turnoP1){
            txtTurno.setForeground(Nav.game.player2.getColor());
            turnoP1 = false;
        } else {
            txtTurno.setForeground(Nav.game.player1.getColor());
            turnoP1 = true;
        }
        movimientos++;
        txtMov.setText(String.valueOf(movimientos));
        btn06.setText(txtTurno.getText());
        btn06.setEnabled(false);
        Nav.board.colocarFicha();
        if("X".equals(txtTurno.getText())){
            tab5x5[1][0] = 1;
        } else {
            tab5x5[1][0] = 2;
        }
        ganador = Nav.game.hayGanador5x5(tab5x5);
        Nav.game.elegirGanador(ganador, movimientos);
    }//GEN-LAST:event_btn06ActionPerformed

    private void btn02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn02ActionPerformed
        if(turnoP1){
            txtTurno.setForeground(Nav.game.player2.getColor());
            turnoP1 = false;
        } else {
            txtTurno.setForeground(Nav.game.player1.getColor());
            turnoP1 = true;
        }
        movimientos++;
        txtMov.setText(String.valueOf(movimientos));
        btn02.setText(txtTurno.getText());
        btn02.setEnabled(false);
        Nav.board.colocarFicha();
        if("X".equals(txtTurno.getText())){
            tab5x5[0][1] = 1;
        } else {
            tab5x5[0][1] = 2;
        }
        ganador = Nav.game.hayGanador5x5(tab5x5);
        Nav.game.elegirGanador(ganador, movimientos);
    }//GEN-LAST:event_btn02ActionPerformed

    private void btn03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn03ActionPerformed
        if(turnoP1){
            txtTurno.setForeground(Nav.game.player2.getColor());
            turnoP1 = false;
        } else {
            txtTurno.setForeground(Nav.game.player1.getColor());
            turnoP1 = true;
        }
        movimientos++;
        txtMov.setText(String.valueOf(movimientos));
        btn03.setText(txtTurno.getText());
        btn03.setEnabled(false);
        Nav.board.colocarFicha();
        if("X".equals(txtTurno.getText())){
            tab5x5[0][2] = 1;
        } else {
            tab5x5[0][2] = 2;
        }
        ganador = Nav.game.hayGanador5x5(tab5x5);
        Nav.game.elegirGanador(ganador, movimientos);
    }//GEN-LAST:event_btn03ActionPerformed

    private void btn04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn04ActionPerformed
        if(turnoP1){
            txtTurno.setForeground(Nav.game.player2.getColor());
            turnoP1 = false;
        } else {
            txtTurno.setForeground(Nav.game.player1.getColor());
            turnoP1 = true;
        }
        movimientos++;
        txtMov.setText(String.valueOf(movimientos));
        btn04.setText(txtTurno.getText());
        btn04.setEnabled(false);
        Nav.board.colocarFicha();
        if("X".equals(txtTurno.getText())){
            tab5x5[0][3] = 1;
        } else {
            tab5x5[0][3] = 2;
        }
        ganador = Nav.game.hayGanador5x5(tab5x5);
        Nav.game.elegirGanador(ganador, movimientos);
    }//GEN-LAST:event_btn04ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Nav.board.reiniciarTablero();
        this.setVisible(false);
        Nav.gui.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn21ActionPerformed
        if(turnoP1){
            txtTurno.setForeground(Nav.game.player2.getColor());
            turnoP1 = false;
        } else {
            txtTurno.setForeground(Nav.game.player1.getColor());
            turnoP1 = true;
        }
        movimientos++;
        txtMov.setText(String.valueOf(movimientos));
        btn21.setText(txtTurno.getText());
        btn21.setEnabled(false);
        Nav.board.colocarFicha();
        if("X".equals(txtTurno.getText())){
            tab5x5[4][0] = 1;
        } else {
            tab5x5[4][0] = 2;
        }
        ganador = Nav.game.hayGanador5x5(tab5x5);
        Nav.game.elegirGanador(ganador, movimientos);
    }//GEN-LAST:event_btn21ActionPerformed

    private void btn05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn05ActionPerformed
        if(turnoP1){
            txtTurno.setForeground(Nav.game.player2.getColor());
            turnoP1 = false;
        } else {
            txtTurno.setForeground(Nav.game.player1.getColor());
            turnoP1 = true;
        }
        movimientos++;
        txtMov.setText(String.valueOf(movimientos));
        btn05.setText(txtTurno.getText());
        btn05.setEnabled(false);
        Nav.board.colocarFicha();
        if("X".equals(txtTurno.getText())){
            tab5x5[0][4] = 1;
        } else {
            tab5x5[0][4] = 2;
        }
        ganador = Nav.game.hayGanador5x5(tab5x5);
        Nav.game.elegirGanador(ganador, movimientos);
    }//GEN-LAST:event_btn05ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        if(turnoP1){
            txtTurno.setForeground(Nav.game.player2.getColor());
            turnoP1 = false;
        } else {
            txtTurno.setForeground(Nav.game.player1.getColor());
            turnoP1 = true;
        }
        movimientos++;
        txtMov.setText(String.valueOf(movimientos));
        btn10.setText(txtTurno.getText());
        btn10.setEnabled(false);
        Nav.board.colocarFicha();
        if("X".equals(txtTurno.getText())){
            tab5x5[1][4] = 1;
        } else {
            tab5x5[1][4] = 2;
        }
        ganador = Nav.game.hayGanador5x5(tab5x5);
        Nav.game.elegirGanador(ganador, movimientos);
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn15ActionPerformed
        if(turnoP1){
            txtTurno.setForeground(Nav.game.player2.getColor());
            turnoP1 = false;
        } else {
            txtTurno.setForeground(Nav.game.player1.getColor());
            turnoP1 = true;
        }
        movimientos++;
        txtMov.setText(String.valueOf(movimientos));
        btn15.setText(txtTurno.getText());
        btn15.setEnabled(false);
        Nav.board.colocarFicha();
        if("X".equals(txtTurno.getText())){
            tab5x5[2][4] = 1;
        } else {
            tab5x5[2][4] = 2;
        }
        ganador = Nav.game.hayGanador5x5(tab5x5);
        Nav.game.elegirGanador(ganador, movimientos);
    }//GEN-LAST:event_btn15ActionPerformed

    private void btn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn20ActionPerformed
        if(turnoP1){
            txtTurno.setForeground(Nav.game.player2.getColor());
            turnoP1 = false;
        } else {
            txtTurno.setForeground(Nav.game.player1.getColor());
            turnoP1 = true;
        }
        movimientos++;
        txtMov.setText(String.valueOf(movimientos));
        btn20.setText(txtTurno.getText());
        btn20.setEnabled(false);
        Nav.board.colocarFicha();
        if("X".equals(txtTurno.getText())){
            tab5x5[3][4] = 1;
        } else {
            tab5x5[3][4] = 2;
        }
        ganador = Nav.game.hayGanador5x5(tab5x5);
        Nav.game.elegirGanador(ganador, movimientos);
    }//GEN-LAST:event_btn20ActionPerformed

    private void btn25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn25ActionPerformed
        if(turnoP1){
            txtTurno.setForeground(Nav.game.player2.getColor());
            turnoP1 = false;
        } else {
            txtTurno.setForeground(Nav.game.player1.getColor());
            turnoP1 = true;
        }
        movimientos++;
        txtMov.setText(String.valueOf(movimientos));
        btn25.setText(txtTurno.getText());
        btn25.setEnabled(false);
        Nav.board.colocarFicha();
        if("X".equals(txtTurno.getText())){
            tab5x5[4][4] = 1;
        } else {
            tab5x5[4][4] = 2;
        }
        ganador = Nav.game.hayGanador5x5(tab5x5);
        Nav.game.elegirGanador(ganador, movimientos);
    }//GEN-LAST:event_btn25ActionPerformed

    private void btn24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn24ActionPerformed
        if(turnoP1){
            txtTurno.setForeground(Nav.game.player2.getColor());
            turnoP1 = false;
        } else {
            txtTurno.setForeground(Nav.game.player1.getColor());
            turnoP1 = true;
        }
        movimientos++;
        txtMov.setText(String.valueOf(movimientos));
        btn24.setText(txtTurno.getText());
        btn24.setEnabled(false);
        Nav.board.colocarFicha();
        if("X".equals(txtTurno.getText())){
            tab5x5[4][3] = 1;
        } else {
            tab5x5[4][3] = 2;
        }
        ganador = Nav.game.hayGanador5x5(tab5x5);
        Nav.game.elegirGanador(ganador, movimientos);
    }//GEN-LAST:event_btn24ActionPerformed

    private void btn23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn23ActionPerformed
        if(turnoP1){
            txtTurno.setForeground(Nav.game.player2.getColor());
            turnoP1 = false;
        } else {
            txtTurno.setForeground(Nav.game.player1.getColor());
            turnoP1 = true;
        }
        movimientos++;
        txtMov.setText(String.valueOf(movimientos));
        btn23.setText(txtTurno.getText());
        btn23.setEnabled(false);
        Nav.board.colocarFicha();
        if("X".equals(txtTurno.getText())){
            tab5x5[4][2] = 1;
        } else {
            tab5x5[4][2] = 2;
        }
        ganador = Nav.game.hayGanador5x5(tab5x5);
        Nav.game.elegirGanador(ganador, movimientos);
    }//GEN-LAST:event_btn23ActionPerformed

    private void btn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn22ActionPerformed
        if(turnoP1){
            txtTurno.setForeground(Nav.game.player2.getColor());
            turnoP1 = false;
        } else {
            txtTurno.setForeground(Nav.game.player1.getColor());
            turnoP1 = true;
        }
        movimientos++;
        txtMov.setText(String.valueOf(movimientos));
        btn22.setText(txtTurno.getText());
        btn22.setEnabled(false);
        Nav.board.colocarFicha();
        if("X".equals(txtTurno.getText())){
            tab5x5[4][1] = 1;
        } else {
            tab5x5[4][1] = 2;
        }
        ganador = Nav.game.hayGanador5x5(tab5x5);
        Nav.game.elegirGanador(ganador, movimientos);
    }//GEN-LAST:event_btn22ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JToggleButton btn01;
    public javax.swing.JToggleButton btn02;
    public javax.swing.JToggleButton btn03;
    public javax.swing.JToggleButton btn04;
    public javax.swing.JToggleButton btn05;
    public javax.swing.JToggleButton btn06;
    public javax.swing.JToggleButton btn07;
    public javax.swing.JToggleButton btn08;
    public javax.swing.JToggleButton btn09;
    public javax.swing.JToggleButton btn10;
    public javax.swing.JToggleButton btn11;
    public javax.swing.JToggleButton btn12;
    public javax.swing.JToggleButton btn13;
    public javax.swing.JToggleButton btn14;
    public javax.swing.JToggleButton btn15;
    public javax.swing.JToggleButton btn16;
    public javax.swing.JToggleButton btn17;
    public javax.swing.JToggleButton btn18;
    public javax.swing.JToggleButton btn19;
    public javax.swing.JToggleButton btn20;
    public javax.swing.JToggleButton btn21;
    public javax.swing.JToggleButton btn22;
    public javax.swing.JToggleButton btn23;
    public javax.swing.JToggleButton btn24;
    public javax.swing.JToggleButton btn25;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel txtMov;
    public javax.swing.JLabel txtTamaño;
    public javax.swing.JLabel txtTurno;
    // End of variables declaration//GEN-END:variables
}
