package GUI;
import Class.Navegador;
import javax.swing.JOptionPane;
public class Game3x3 extends javax.swing.JFrame {
    Navegador Nav;
    public int tab3x3[][];
    int ganador;
    int movimientos = 0;
    boolean turnoP1 = true;
    boolean turnoP2 = false;
    public Game3x3(Navegador n) {
        initComponents();
        tab3x3 = new int[3][3];
        txtMov.setText(String.valueOf(movimientos));
        Nav = n;
        if(Nav.gui.chkCircle1.isSelected()){
            txtTurno.setText("X");
        } else {
            txtTurno.setText("O");
        }
    }

    public boolean isTurnoP1() {
        return turnoP1;
    }

    public void setTurnoP1(boolean turnoP1) {
        this.turnoP1 = turnoP1;
    }

    public boolean isTurnoP2() {
        return turnoP2;
    }

    public void setTurnoP2(boolean turnoP2) {
        this.turnoP2 = turnoP2;
    }

    public int getMovimientos() {
        return movimientos;
    }

    public void setMovimientos(int movimientos) {
        this.movimientos = movimientos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn01 = new javax.swing.JToggleButton();
        btn02 = new javax.swing.JToggleButton();
        btn06 = new javax.swing.JToggleButton();
        btn07 = new javax.swing.JToggleButton();
        btn09 = new javax.swing.JToggleButton();
        btn04 = new javax.swing.JToggleButton();
        btn05 = new javax.swing.JToggleButton();
        btn08 = new javax.swing.JToggleButton();
        txtTamaño = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTurno = new javax.swing.JLabel();
        txtMov = new javax.swing.JLabel();
        btn03 = new javax.swing.JToggleButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn01.setBackground(new java.awt.Color(204, 204, 204));
        btn01.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        btn01.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn01ActionPerformed(evt);
            }
        });
        getContentPane().add(btn01, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 70, 70));

        btn02.setBackground(new java.awt.Color(204, 204, 204));
        btn02.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        btn02.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn02ActionPerformed(evt);
            }
        });
        getContentPane().add(btn02, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 70, 70));

        btn06.setBackground(new java.awt.Color(204, 204, 204));
        btn06.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        btn06.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn06ActionPerformed(evt);
            }
        });
        getContentPane().add(btn06, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 70, 70));

        btn07.setBackground(new java.awt.Color(204, 204, 204));
        btn07.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        btn07.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn07ActionPerformed(evt);
            }
        });
        getContentPane().add(btn07, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 70, 70));

        btn09.setBackground(new java.awt.Color(204, 204, 204));
        btn09.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        btn09.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn09ActionPerformed(evt);
            }
        });
        getContentPane().add(btn09, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 70, 70));

        btn04.setBackground(new java.awt.Color(204, 204, 204));
        btn04.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        btn04.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn04ActionPerformed(evt);
            }
        });
        getContentPane().add(btn04, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 70, 70));

        btn05.setBackground(new java.awt.Color(204, 204, 204));
        btn05.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        btn05.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn05ActionPerformed(evt);
            }
        });
        getContentPane().add(btn05, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 70, 70));

        btn08.setBackground(new java.awt.Color(204, 204, 204));
        btn08.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        btn08.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn08ActionPerformed(evt);
            }
        });
        getContentPane().add(btn08, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 70, 70));

        txtTamaño.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        txtTamaño.setForeground(new java.awt.Color(255, 0, 0));
        txtTamaño.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTamaño.setText("3x3");
        txtTamaño.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(txtTamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 70, -1));

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("TURNO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 10));

        txtTurno.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTurno.setForeground(new java.awt.Color(255, 0, 0));
        txtTurno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTurno.setText("00");
        txtTurno.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(txtTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 60, 40));

        txtMov.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtMov.setForeground(new java.awt.Color(255, 0, 0));
        txtMov.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMov.setText("00");
        getContentPane().add(txtMov, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 40, 50));

        btn03.setBackground(new java.awt.Color(204, 204, 204));
        btn03.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        btn03.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn03ActionPerformed(evt);
            }
        });
        getContentPane().add(btn03, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 70, 70));

        btnBack.setBackground(new java.awt.Color(204, 204, 204));
        btnBack.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 0, 0));
        btnBack.setText("Menú principal");
        btnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 110, 30));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 30, 0));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn01ActionPerformed
        if(turnoP1){
            txtTurno.setForeground(Nav.game.player2.getColor());
            turnoP1 = false;
        } else {
            txtTurno.setForeground(Nav.game.player1.getColor());
            turnoP1 = true;
        }
        movimientos++;
        txtMov.setText(String.valueOf(movimientos));
        btn01.setText(txtTurno.getText());
        btn01.setEnabled(false);
        Nav.board.colocarFicha();
                if("X".equals(txtTurno.getText())){
                    tab3x3[0][0] = 1;
                    ganador = Nav.game.hayGanador3x3(tab3x3);
                } else {
                    tab3x3[0][0] = 2;
                    ganador = Nav.game.hayGanador3x3(tab3x3);
                }
        Nav.game.elegirGanador(ganador, movimientos);
    }//GEN-LAST:event_btn01ActionPerformed

    private void btn02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn02ActionPerformed
        if(turnoP1){
            txtTurno.setForeground(Nav.game.player2.getColor());
            turnoP1 = false;
        } else {
            txtTurno.setForeground(Nav.game.player1.getColor());
            turnoP1 = true;
        }
        movimientos++;
        txtMov.setText(String.valueOf(movimientos));
        btn02.setText(txtTurno.getText());
        btn02.setEnabled(false);
        Nav.board.colocarFicha();
                if("X".equals(txtTurno.getText())){
                    tab3x3[0][1] = 1;
                    ganador = Nav.game.hayGanador3x3(tab3x3);
                } else {
                    tab3x3[0][1] = 2;
                    ganador = Nav.game.hayGanador3x3(tab3x3);
                }
        Nav.game.elegirGanador(ganador, movimientos);
    }//GEN-LAST:event_btn02ActionPerformed

    private void btn04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn04ActionPerformed
        if(turnoP1){
            txtTurno.setForeground(Nav.game.player2.getColor());
            turnoP1 = false;
        } else {
            txtTurno.setForeground(Nav.game.player1.getColor());
            turnoP1 = true;
        }
        movimientos++;
        txtMov.setText(String.valueOf(movimientos));
        btn04.setText(txtTurno.getText());
        btn04.setEnabled(false);
        Nav.board.colocarFicha();
                if("X".equals(txtTurno.getText())){
                    tab3x3[1][0] = 1;
                    ganador = Nav.game.hayGanador3x3(tab3x3);
                } else {
                    tab3x3[1][0] = 2;
                    ganador = Nav.game.hayGanador3x3(tab3x3);
                }
        Nav.game.elegirGanador(ganador, movimientos);
    }//GEN-LAST:event_btn04ActionPerformed

    private void btn05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn05ActionPerformed
        if(turnoP1){
            txtTurno.setForeground(Nav.game.player2.getColor());
            turnoP1 = false;
        } else {
            txtTurno.setForeground(Nav.game.player1.getColor());
            turnoP1 = true;
        }
        movimientos++;
        txtMov.setText(String.valueOf(movimientos));
        btn05.setText(txtTurno.getText());
        btn05.setEnabled(false);
        Nav.board.colocarFicha();
                if("X".equals(txtTurno.getText())){
                    tab3x3[1][1] = 1;
                    ganador = Nav.game.hayGanador3x3(tab3x3);
                } else {
                    tab3x3[1][1] = 2;
                    ganador = Nav.game.hayGanador3x3(tab3x3);
                }
        Nav.game.elegirGanador(ganador, movimientos);
    }//GEN-LAST:event_btn05ActionPerformed

    private void btn06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn06ActionPerformed
        if(turnoP1){
            txtTurno.setForeground(Nav.game.player2.getColor());
            turnoP1 = false;
        } else {
            txtTurno.setForeground(Nav.game.player1.getColor());
            turnoP1 = true;
        }
        movimientos++;
        txtMov.setText(String.valueOf(movimientos));
        btn06.setText(txtTurno.getText());
        btn06.setEnabled(false);
        Nav.board.colocarFicha();
                if("X".equals(txtTurno.getText())){
                    tab3x3[1][2] = 1;
                    ganador = Nav.game.hayGanador3x3(tab3x3);
                } else {
                    tab3x3[1][2] = 2;
                    ganador = Nav.game.hayGanador3x3(tab3x3);
                }
        Nav.game.elegirGanador(ganador, movimientos);
    }//GEN-LAST:event_btn06ActionPerformed

    private void btn07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn07ActionPerformed
        if(turnoP1){
            txtTurno.setForeground(Nav.game.player2.getColor());
            turnoP1 = false;
        } else {
            txtTurno.setForeground(Nav.game.player1.getColor());
            turnoP1 = true;
        }
        movimientos++;
        txtMov.setText(String.valueOf(movimientos));
        btn07.setText(txtTurno.getText());
        btn07.setEnabled(false);
        Nav.board.colocarFicha();
                if("X".equals(txtTurno.getText())){
                    tab3x3[2][0] = 1;
                    ganador = Nav.game.hayGanador3x3(tab3x3);
                } else {
                    tab3x3[2][0] = 2;
                    ganador = Nav.game.hayGanador3x3(tab3x3);
                }
        Nav.game.elegirGanador(ganador, movimientos);
    }//GEN-LAST:event_btn07ActionPerformed

    private void btn08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn08ActionPerformed
        if(turnoP1){
            txtTurno.setForeground(Nav.game.player2.getColor());
            turnoP1 = false;
        } else {
            txtTurno.setForeground(Nav.game.player1.getColor());
            turnoP1 = true;
        }
        movimientos++;
        txtMov.setText(String.valueOf(movimientos));
        btn08.setText(txtTurno.getText());
        btn08.setEnabled(false);
        Nav.board.colocarFicha();
                if("X".equals(txtTurno.getText())){
                    tab3x3[2][1] = 1;
                    ganador = Nav.game.hayGanador3x3(tab3x3);
                } else {
                    tab3x3[2][1] = 2;
                    ganador = Nav.game.hayGanador3x3(tab3x3);
                }
        Nav.game.elegirGanador(ganador, movimientos);
    }//GEN-LAST:event_btn08ActionPerformed

    private void btn09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn09ActionPerformed
        if(turnoP1){
            txtTurno.setForeground(Nav.game.player2.getColor());
            turnoP1 = false;
        } else {
            txtTurno.setForeground(Nav.game.player1.getColor());
            turnoP1 = true;
        }
        movimientos++;
        txtMov.setText(String.valueOf(movimientos));
        btn09.setText(txtTurno.getText());
        btn09.setEnabled(false);
        Nav.board.colocarFicha();
                if("X".equals(txtTurno.getText())){
                    tab3x3[2][2] = 1;
                    ganador = Nav.game.hayGanador3x3(tab3x3);
                } else {
                    tab3x3[2][2] = 2;
                    ganador = Nav.game.hayGanador3x3(tab3x3);
                }
        Nav.game.elegirGanador(ganador, movimientos);
    }//GEN-LAST:event_btn09ActionPerformed

    private void btn03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn03ActionPerformed
        if(turnoP1){
            txtTurno.setForeground(Nav.game.player2.getColor());
            turnoP1 = false;
        } else {
            txtTurno.setForeground(Nav.game.player1.getColor());
            turnoP1 = true;
        }
        movimientos++;
        txtMov.setText(String.valueOf(movimientos));
        btn03.setText(txtTurno.getText());
        btn03.setEnabled(false);
        Nav.board.colocarFicha();
                if("X".equals(txtTurno.getText())){
                    tab3x3[0][2] = 1;
                    ganador = Nav.game.hayGanador3x3(tab3x3);
                } else {
                    tab3x3[0][2] = 2;
                    ganador = Nav.game.hayGanador3x3(tab3x3);
                }
        Nav.game.elegirGanador(ganador, movimientos);
    }//GEN-LAST:event_btn03ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       Nav.board.reiniciarTablero();
       this.setVisible(false);
       Nav.gui.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JToggleButton btn01;
    public javax.swing.JToggleButton btn02;
    public javax.swing.JToggleButton btn03;
    public javax.swing.JToggleButton btn04;
    public javax.swing.JToggleButton btn05;
    public javax.swing.JToggleButton btn06;
    public javax.swing.JToggleButton btn07;
    public javax.swing.JToggleButton btn08;
    public javax.swing.JToggleButton btn09;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel txtMov;
    public javax.swing.JLabel txtTamaño;
    public javax.swing.JLabel txtTurno;
    // End of variables declaration//GEN-END:variables
}
