
package GUI;

import Class.Navegador;

public class Principal extends javax.swing.JFrame {
    Navegador Nav;
    public Principal(Navegador n) {
        initComponents();
        Nav = n;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        brnGPlayer1 = new javax.swing.ButtonGroup();
        btnGPlayer2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbTablero = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtPlayer1 = new javax.swing.JTextField();
        cbColor1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtPlayer2 = new javax.swing.JTextField();
        cbColor2 = new javax.swing.JComboBox<>();
        btnStart = new javax.swing.JButton();
        chkCircle1 = new javax.swing.JCheckBox();
        chkExs1 = new javax.swing.JCheckBox();
        chkCircle2 = new javax.swing.JCheckBox();
        chkExs2 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TRIQUITRAQUE");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 380, 50));

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("JUGADOR 1");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, -1));

        cbTablero.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        cbTablero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DEFAULT (3x3)", "4x4", "5x5" }));
        getContentPane().add(cbTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, 160, 70));

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("TIPO DE TABLERO");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, 70));

        txtPlayer1.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        getContentPane().add(txtPlayer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 260, 30));

        cbColor1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COLOR", "NEGRO", "AZUL", "AMARILLO", "MARRON", "GRIS", "VERDE", "NARANJA", "ROSA", "PURPURA", "ROJO" }));
        getContentPane().add(cbColor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 150, 30));

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("JUGADOR 2");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, -1));

        txtPlayer2.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        getContentPane().add(txtPlayer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 260, 30));

        cbColor2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COLOR", "NEGRO", "AZUL", "AMARILLO", "MARRON", "GRIS", "VERDE", "NARANJA", "ROSA", "PURPURA", "ROJO" }));
        getContentPane().add(cbColor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 150, 30));

        btnStart.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        btnStart.setForeground(new java.awt.Color(255, 0, 0));
        btnStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Nero_Smart_Start_22551.png"))); // NOI18N
        btnStart.setText("INICIAR PARTIDA");
        btnStart.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        getContentPane().add(btnStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 220, 50));

        brnGPlayer1.add(chkCircle1);
        getContentPane().add(chkCircle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 30, 30));

        brnGPlayer1.add(chkExs1);
        getContentPane().add(chkExs1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 30, 30));

        btnGPlayer2.add(chkCircle2);
        getContentPane().add(chkCircle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 30, 30));

        btnGPlayer2.add(chkExs2);
        getContentPane().add(chkExs2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 30, 30));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 90, 20));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel7.setText("O");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel9.setText("X");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Nombre");
        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("Nombre");
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 273, 830, 10));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 420, -1, 10));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 330, 40, 10));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel14.setText("O");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel15.setText("X");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        Nav.game.iniciarPartida();
    }//GEN-LAST:event_btnStartActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup brnGPlayer1;
    private javax.swing.ButtonGroup btnGPlayer2;
    public javax.swing.JButton btnStart;
    public javax.swing.JComboBox<String> cbColor1;
    public javax.swing.JComboBox<String> cbColor2;
    public javax.swing.JComboBox<String> cbTablero;
    public javax.swing.JCheckBox chkCircle1;
    public javax.swing.JCheckBox chkCircle2;
    public javax.swing.JCheckBox chkExs1;
    public javax.swing.JCheckBox chkExs2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator4;
    public javax.swing.JTextField txtPlayer1;
    public javax.swing.JTextField txtPlayer2;
    // End of variables declaration//GEN-END:variables
}
